[connections.Snowflake]
type = "snowflake"
account = "ULLPRBD-TVB94173"
user = "OmayrQ786"
password = "Ghousia@123456"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
role = "SYSADMIN"
client_session_keep_alive = true
